server:
  port: 8081
spring:
  application:
    name: microservice-customer
    # datasource:
      #driver-class-name: com.mysql.jdbc.Driver
      # url: jdbc:mysql://localhost:3306/TESTDB?useUnicode=true&characterEncoding=true
      #url: jdbc:mysql://localhost:8066/TESTDB?useUnicode=true&characterEncoding=true
      #data-username: root
      #data-password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: false

#mybatis:
#  type-aliases-package: com.customer.demo.dao
#  mapper-locations: classpath:/mybatis/*.xml

