server:
  port: 8080
spring:
  application:
    name: microservice-privoder
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: false

