server:
  port: 8082
spring:
  application:
    name: microservice-customer-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: false
#ribbon
getUser:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: 'hystrix.stream'
#ribbon:
#  eager-load:
#    enabled: true
#    clients: microservice-privoder